[package]
name = "pdfx"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.46", features = ["derive"] }
dirs = "6.0.0"
indicatif = "0.18.0"
lopdf = "0.37.0"
rusqlite = "0.37.0"
serde = "1.0.219"
walkdir = "2.5.0"
