name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Run security audit
      run: cargo audit
